# Use the official NGINX image from Docker Hub
FROM nginx:alpine

# Copy the contents of the public folder to the default NGINX directory
COPY public /usr/share/nginx/html

# Expose port 80
EXPOSE 80
