  services:
    db:
      image: mariadb:latest
      environment:
        MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
        MYSQL_DATABASE: ${DB_DATABASE}
        MYSQL_USER: ${DB_USERNAME}
        MYSQL_PASSWORD: ${DB_PASSWORD}
      volumes:
        - ./db/init:/docker-entrypoint-initdb.d
      networks:
        - app-network

    node-service:
      build: ./api
      environment:
        DB_HOST: ${DB_HOST}
        DB_DATABASE: ${DB_DATABASE}
        DB_USERNAME: ${DB_USERNAME}
        DB_PASSWORD: ${DB_PASSWORD}
      networks:
        - app-network
      depends_on:
        - db

    nginx:
      build: ./nginx
      ports:
        - "8080:80"
      networks:
        - app-network
      depends_on:
        - node-service

  networks:
    app-network:
      driver: bridge